### ISSUE TITLE
getting python error

### ISSUE THREAD

**Issue by Alex71btc** [AngusP/phoenixd-lnurl#13]
hey,I tried to upgrade to your latest version of phoenixd-lnurl but with new version running from container ( in Portainer) i always get the error: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'
seems to be some python version error, any idea?
[_Phoenixd-lnurl_logs(1).txt](https://github.com/user-attachments/files/15826494/_Phoenixd-lnurl_logs.1.txt)

**Comment by AngusP** [comment]
Hey, just to check, are you using the image `ghcr.io/angusp/phoenixd-lnurl:latest`?

But yeah that does look like some issue with a package has appeared, I'll see if I can replicate the issue and resolve it quickly for you -- should hopefully just need some package updates

**Comment by Alex71btc** [comment]
Yes I tried that package and also all other packages since last month fail.The old  package from one month ago still works. So went back.

**Comment by Alex71btc** [comment]
FYI running the container in portainer app on umbrel home server( portainer version 2.19.1) if that info herzlos helps to reproduce...

**Comment by AngusP** [comment]
Hrm, seems like it might be an issue specifically with pydantic (a dependency) and Pyhton 3.12 `https://github.com/pydantic/pydantic-core/pull/1299`

"Just" downgrading to Python 3.11 for now seems to fix it, I'm stuck on an older version of Pydantic for now to maintain compatibility with the lnurl package -- I'll merge a fix soon and then the `:latest` Docker image should work again

**Comment by AngusP** [comment]
@Funman2 thanks for the report, hopefully the `:latest` resolves for you (did for me!) but feel free to reopen if not 🤝

**Comment by Alex71btc** [comment]
Yes it works now, thanks very much for the really quick fix! 
Does this packet version have some sort of nostr zap support already included?

**Comment by AngusP** [comment]
>  Does this packet version have some sort of nostr zap support already included?

Not yet, working on it in #11 -- it was blocked for a bit on an issue n `phoenixd` that's now been resolved (it would crash/hang on really big invoice descriptions, which is kinda what zaps are) so I just need to get around to finishing that pull request then we'll have proper zaps.
