### ISSUE TITLE
Consider mounting config file instead of adding at build time

### ISSUE THREAD

**Issue by sethforprivacy** [AngusP/phoenixd-lnurl#3]
https://github.com/AngusP/phoenixd-lnurl/blob/f5b0bd343fb2670ad10998946764ff3e874f9fee/Dockerfile#L9 sets the env file at build time, but for portability and easier image distribution, I'd highly recommend removing this and instead exposing a volume for the end-user to mount a config file into.

I.e.

```
# Expose default data directory as VOLUME
VOLUME [ "/var/phoenixd_lnurl" ]
```

**Comment by AngusP** [comment]
Alternatively, all the values in the `.env` file can be preferentially overwritten by environment variables, so config can 'just' be supplied to the container that way. I don't have a strong opinion for which is better, perhaps supporting both is best?

**Comment by sethforprivacy** [comment]
Supporting both is best, but much prefer environment variables! I hadn't tested that, but will definitely use that moving forward.

**Comment by AngusP** [comment]
I'll add that you can use env variables to the README, it's not obvious if you're not familiar with [pydantic-settings](https://docs.pydantic.dev/latest/concepts/pydantic_settings/#dotenv-env-support).

*Some* `phoenixd-lnurl.env` will have to exist, but it can be boilerplate in the Docker container (like `satoshi@example.com`)

**Comment by AngusP** [comment]
Completed as #7 documents how to configure with env variables; this seems easier/good enough to me for now to not bother with a volume for the `.env`?
